[theme]
primaryColor = "#f63366"

backgroundColor = "#000000"
# secondaryBackgroundColor = "#dab6db"
secondaryBackgroundColor = "rgba(255, 255, 255, 0.1)"
textColor = "#fafafa"


[server]
enableStaticServing = true