[theme]
primaryColor = "#f63366"

backgroundColor = "#000000"
# secondaryBackgroundColor = "#dab6db"
secondaryBackgroundColor = "rgb(255, 255, 255)"
textColor = "#fafafa"


[server]
enableStaticServing = true