[theme]
primaryColor = "#06661b"
backgroundColor = "#000000"
secondaryBackgroundColor = "#dab6db"
secondaryBackgroundColor = "rgb(79, 79, 79)"
textColor = "#fafafa"


[server]
enableStaticServing = true